### ISSUE TITLE
NPM package already taken

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#1]
Hi @Download,
I kinda tried reaching you over mail but had little luck.
I guess you and I are working over similar thing `preact-material-component`.
Please take a look at the repo and let me know if it kinda aligns to your vision of the same.
I'd be happy to add you as a collaborator.

Currently you are owning the package `preact-material-component` @ NPM, it'd be great if we can share the release rights and contribute to these components.

P.S.: This repo largely derives is base from `preact-mdl`.

**Comment by Download** [comment]
Hi @prateekbh 
Wow yes it looks like we are working on the same stuff.

I would be happy to share the package name, but:
1) A package `preact-mdl` already exists
2) I have (pretty strict) ideas about what I want with this package. 

My ideas: I want to create a version of material-components-web for preact that:
1) Does not rely on JS for the client side (so if JS is disabled on the browser, it should still work)
2) Should be compatible with AMP

My reasons for this are that a.t.m., material-components-web supports neither of these features. I am developing a universal/isomorphic app, so everything is server rendered and the client rendering is fully optional and I would like my server to automatically generate AMP versions of my pages *based on the same gui components as the main site*. Since AMP does not allow custom JS to be inserted in the page (only AMP js), we can not use the standard material-components-web scripts.

So a straight port of react-mdl or a simple wrapper around material-components-web in the same manner as react-mdl did is not what I am looking for.

Can you tell me more about the goals of your project?

**Comment by prateekbh** [comment]
Thanks for the time @Download, I see what you are trying to build and is a really nice idea.
I am happy to put down my ideas and Goals fro this Repo:

Both`preact-mdl` and `preact-material-components` are based on the similar idea of `Thinnest Wrapper over the underlying library for the perfect ease` of use of the same.

However `preact-mdl` or even `material design lite` are not very breakable into smaller chunks for usage. Imagine someone using just a Button, Fab, Snackbar for their project, they still take the load of every other component.

`material-component-web` however aims bringing material components in an a-la carté fashion.
And `preact-material-components` aims to be do what `preact-mdl` did for mdl.

In a nutshell Super Easy wrapper of `material-components-web` in a way, where you can `Tree-shake` everything you are not using.

I see that I am not really focussing on your key concerns, however if `material-components-web` work without jS `preact-material-components` would too. But I agree my current focus is still not anywhere near AMP.

In this case we can do one of the following two things:

 1. I can go ahead and use another package like *preact-material-components-web*
 2. If you think this repo is more aligned with *material-components-web*, may be you can tweek your package name.
 3. If *material-components-web* gracefully degrades without jS (which I haven't checked for each and every control) we can talk about how to just make it work with AMP and still keep on collaborating in this repo.

**Comment by Download** [comment]
@prateekbh You make a good argument. `material-components-web` is built in a certain way and users would probably expect preact-material-components to do the same thing.

However, I know for a fact that material-components-web is *not* compatible with AMP, because I [checked](https://github.com/material-components/material-components-web/issues/389). I think it's a shame as they are both hot new Google projects targeting the same markets/devices but it's what it is.

Anyway before I start rambling.... How about I give you the namespace on NPM and you make me collaborator on your project? It wil be your project but I would like to come in now and then and make a branch and hack around a bit to see if I can fix the AMP issues where I find them.

> we can talk about how to just make it work with AMP and still keep on collaborating in this repo.

That sounds like the best idea! I suspect a lot will work out of the box, but some components either will need fixing, or we might mark them as not supporting AMP in the docs. And maybe my project could become like and add-on to this one, that replaces some built-ins with different, AMP-compatible versions of those components.

**Comment by Download** [comment]
I got an idea.

I also 'own' the namespace [preact-material](https://www.npmjs.com/package/preact-material). I like it because it's short and sweet. 

I also just grabbed [preact-material-amp](https://www.npmjs.com/package/preact-material-amp).

This might be sweet? Use the components from material-components-web that work well with AMP out of the box (maybe after some small fixes) from `preact-material`, then pull in some alternatives for the ones that don't work with AMP from `preact-material-amp`.

What do you think?

**Comment by prateekbh** [comment]
Great Ideas.
Although the aim of keeping this really lightweight wrapper over `material-component-web` makes me hesitant over the approach of namespace `preact-material/checkbox`.

Even in current implementation you can do 

``` import Checkbox from preact-material-components/checkbox/```

or 

``` import {Checkbox} from preact-material-components // because TreeShaking```

I'd be super happy if we can extend these components to AMP components as well.
I am somehow in favor of keeping the main package as `preact-material-components` and mark individual components as `@AMP Enabled` or vice-versa.

P.S. I have sent you the invite: 
https://github.com/prateekbh/preact-material-components/invitations

**Comment by Download** [comment]
I will leave the choice to you.

I have invited you for the Github project [preact-material](https://github.com/Download/preact-material/invitations)
and made you a collaborator on both the NPM packages [preact-material](https://www.npmjs.com/package/preact-material/) and [preact-material-components](https://www.npmjs.com/package/preact-material-components/).

**Comment by prateekbh** [comment]
Thanks a ton, I'll soon start a gh-pages micro site and ping you to review.
