### ISSUE TITLE
Class undefined in Textfield component

### ISSUE THREAD

**Issue by kbrownhbs** [prateekbh/preact-material-components#147]
I notice there is an "undefined" class in Textfield.  I don't know if this was intentional.  Please first line below. 

![image](https://user-images.githubusercontent.com/3537923/26994155-6c3550c6-4d34-11e7-914c-d64c740542d7.png)

**Comment by jcsmesquita** [comment]
I think this is the `mdc-textfield__label--float-above` class that is not being injected properly and causes the label to remain even after an input value is typed.

**Comment by filoozom** [comment]
@prateekbh could you tell me why you used ```className={className + ""}``` instead of just ```className={className}``` in multiple components including ```Textfield```? I don't really understand in which case it we be useful to cast this variable to a string. Assigning ```undefined``` or ```null``` works without any problems and I don't see why someone would pass an object. Am I missing something?

**Comment by prateekbh** [comment]
@filoozom its a legit bug, I was doing some other concatenation, and forgot to clean it. feel free to remove it and send a PR
