### ISSUE TITLE
Breaks on IE 11

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#202]
need more info here

**Comment by filoozom** [comment]
Did you get to try it? Saw it on Twitter but you didn't have your computer on hand.

**Comment by prateekbh** [comment]
Yeah tried babel need a fix there a object.assign somewhere in the final code

**Comment by keemor** [comment]
Hi,

Bug looks like this in the IE11 console: 
`
SCRIPT1002: Syntax error
File: bundle.js, Line: 4341, Column: 1

4341: class Card extends __WEBPACK_IMPORTED_MODULE_1__MaterialComponent__["a" /* default */] {
  constructor() {
    super();
    this.componentName = "card";
    this._mdcProps = ["theme-dark"];
  }
}
`

Also Uglify reports problem with the same area:
`
ERROR in bundle.js from UglifyJs
Unexpected token: name (Card) [bundle.js:2446,6]

ERROR in bundle.js from UglifyJs
Unexpected token: name (Card) [bundle.js:2446,6]
`

A tried using:
[https://babeljs.io/docs/usage/polyfill/](https://babeljs.io/docs/usage/polyfill/) since it polyfills Object.assign

[https://www.npmjs.com/package/babel-preset-es2015-ie](https://www.npmjs.com/package/babel-preset-es2015-ie)

Then I investigated it from UglifyJS angle:
[https://github.com/webpack/webpack/issues/5449](https://github.com/webpack/webpack/issues/5449)

But changing UglifyJsPlugin  to BabiliPlugin did not help for now.

I'm not sure this is something that can be solved on the application level or must be fixed on PMC level.

Thanks in advance for looking into it.

**Comment by filoozom** [comment]
Works on IE 11 with ```preact-cli```, so I guess this must be a babel / webpack issue on ```gh-pages```?

**Comment by keemor** [comment]
I was trying to compare preact-cli configuration with my project, but I didn't find what makes a difference. 
My:

.babelrc
```
{
  "presets": ["es2015", "stage-0"],
  "plugins": [ 
    "transform-object-assign",
    ["transform-react-jsx", { "pragma":"h" }],
    "transform-react-jsx-source"
  ]
}
```

package.json
```
...
"dependencies": {},
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.28.4",
    "eslint": "^3.19.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-prettier": "^2.1.1",
    "eslint-plugin-react": "^7.0.1",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.28.0",
    "linkref": "^1.0.1",
    "node-sass": "^4.5.3",
    "preact": "^8.1.0",
    "preact-material-components": "^1.1.1",
    "preact-router": "^2.5.2",
    "prettier": "^1.3.1",
    "promise-polyfill": "^6.0.2",
    "sass-loader": "^6.0.5",
    "style-loader": "^0.18.1",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.4.5",
    "whatwg-fetch": "^2.0.3"
  },
...
```
```
...
module: {
        loaders: [            
            {
                test: /\.js$/,
                exclude: [/node_modules/],                
                use: ['babel-loader']
            },
...
```

Any hints?

**Comment by prateekbh** [comment]
`preact-cli` uses something else for webpack, may be that

**Comment by keemor** [comment]
I've made it work.

1. I removed `exclude: [/node_modules/],` from `package.json`
(I was afraid that it will make bundle.js much bigger but the size dropped by 50% -> 450->300KB)

2. In `babel.rc` I changed presets to `env` and added plugin  `"transform-object-rest-spread",`
( I removed babel-preset-es2015 & babel-preset-stage-0)

```
{ 
"presets": ["env"],
"plugins": [
    "transform-object-rest-spread",
    "transform-object-assign",
    ["transform-react-jsx", { "pragma":"h" }],
    "transform-react-jsx-source"
  ]
}
```
And it started to work.

3. Missing Promise added with `"babel-polyfill"` into entry Array in `webpack.js`
(Must be in `"dependencies"` instead of `"devDependencies"`)

4. Finally I had to also add polyfill to fetch method by adding `whatwg-fetch` to entry  Array in `webpack.js`

webpack.js

```
const publicPath = '/';
module.exports = {
    devtool: 'cheap-module-source-map',
    entry: ['babel-polyfill', 'whatwg-fetch', './src/index.js'],
    output: {
        path: path.join(__dirname, 'dev'),
        filename: 'bundle.js',
        publicPath: publicPath
    },
    plugins: [],
    module: {
        loaders: [          
            {
                test: /\.js$/,
                use: ['babel-loader']
            },
```

package.json
```
 "dependencies": {
    "babel-polyfill": "^6.23.0"
  },
  "devDependencies": {
    "babel-core": "^6.24.1",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-plugin-transform-react-jsx-source": "^6.22.0",
    "babel-preset-env": "^1.6.0",
    "css-loader": "^0.28.4",
    "eslint": "^3.19.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-prettier": "^2.1.1",
    "eslint-plugin-react": "^7.0.1",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.28.0",
    "linkref": "^1.0.1",
    "node-sass": "^4.5.3",
    "preact": "^8.1.0",
    "preact-material-components": "^1.1.1",
    "preact-router": "^2.5.2",
    "prettier": "^1.3.1",
    "sass-loader": "^6.0.5",
    "style-loader": "^0.18.1",
    "webpack": "^3.0.0",
    "webpack-dev-server": "^2.4.5",
    "whatwg-fetch": "^2.0.3"
  },
```

**Comment by filoozom** [comment]
To be clear, are you talking about your own project or about ```gh-pages```? I'm closing this issue and replacing it with a new one specifically for ```gh-pages```, because this library does work with IE 11, it's just a matter of configuring ```babel``` and ```webpack``` correctly.
