### ISSUE TITLE
Download not visible in npm

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#28]
Hey @Download 
I publish a version of these components just to try out, but something happened and now you are not visible on the npm page.
can you check the package.json and let me know what went wrong?

**Comment by Download** [comment]
It was a misnamed element in package.json.... I *think*. Not sure actually but I'm guessing this PR will solve it.

**Comment by prateekbh** [comment]
published a new version, still not visible.. :(

**Comment by Download** [comment]
Mmm...

This package of mine had the reverse history... It was owned by someone else who shared it with me.
I published to it many times already, and he is still there on the page:
https://www.npmjs.com/package/ulog

I think maybe it's because my [NPM username](https://www.npmjs.com/~stijndewitt) differs from my [Github username](https://github.com/Download)?

Anyway I don't really mind that I'm not on there. This is your project.  👍
