### ISSUE TITLE
Add chips component

### ISSUE THREAD

**Issue by prateekbh** [prateekbh/preact-material-components#585]
https://github.com/material-components/material-components-web/tree/master/packages/mdc-chips

**Comment by YePpHa** [comment]
I can implement this.

**Comment by YePpHa** [comment]
@prateekbh I got a question regarding on how you want me to export the two classes Chip and ChipSet. The problem is that the package is named Chips and therefore it doesn't make sense to export Chip as default.
Should I export it the same as with the Drawers or should I export them normally: `import { Chip, ChipSet } from '/Chips'`?

**Comment by prateekbh** [comment]
I guess lets just name is `Chips`

and let it hide class `chip-set` from user. User can use `Chips.Chip` for implementation

```
import Chips from 'pmc/Chips'
.
.
.
<Chips>
<Chips.Chip>...</>
<Chips.Chip>...</>
<Chips.Chip>...</>
</Chips>
```

**Comment by YePpHa** [comment]
Okay
